<?
Class Svatek{

  public $den;
  public $mesic;

  public static function svatekMa($den = null, $mesic = null){                     // svatek() = return "Jméno"
    if ($mesic==1) {
      if ($den==1) { return "Nový rok";
      } elseif ($den==2) { return "Karina";
      } elseif ($den==3) { return "Radmila";
      } elseif ($den==4) { return "Diana";
      } elseif ($den==5) { return "Dalimil";
      } elseif ($den==6) { return "Tři králové";
      } elseif ($den==7) { return "Vilma";
      } elseif ($den==8) { return "Čestmír";
      } elseif ($den==9) { return "Vladan";
      } elseif ($den==10) { return "Břetislav";
      } elseif ($den==11) { return "Bohdana";
      } elseif ($den==12) { return "Pravoslav";
      } elseif ($den==13) { return "Edita";
      } elseif ($den==14) { return "Radovan";
      } elseif ($den==15) { return "Alice";
      } elseif ($den==16) { return "Ctirad";
      } elseif ($den==17) { return "Drahoslav";
      } elseif ($den==18) { return "Vladislav";
      } elseif ($den==19) { return "Doubravka";
      } elseif ($den==20) { return "Ilona";
      } elseif ($den==21) { return "Běla";
      } elseif ($den==22) { return "Slavomír";
      } elseif ($den==23) { return "Zdeněk";
      } elseif ($den==24) { return "Milena";
      } elseif ($den==25) { return "Miloš";
      } elseif ($den==26) { return "Zora";
      } elseif ($den==27) { return "Ingrid";
      } elseif ($den==28) { return "Otýlie";
      } elseif ($den==29) { return "Zdislava";
      } elseif ($den==30) { return "Robin";
      } elseif ($den==31) { return "Marika"; }
    } elseif ($mesic==2) {
      if ($den==1) { return "Hynek";
      } elseif ($den==2) { return "Nela";
      } elseif ($den==3) { return "Blažej";
      } elseif ($den==4) { return "Jarmila";
      } elseif ($den==5) { return "Dobromila";
      } elseif ($den==6) { return "Vanda";
      } elseif ($den==7) { return "Veronika";
      } elseif ($den==8) { return "Milada";
      } elseif ($den==9) { return "Apolena";
      } elseif ($den==10) { return "Mojmír";
      } elseif ($den==11) { return "Božena";
      } elseif ($den==12) { return "Slavěna";
      } elseif ($den==13) { return "Věnceslav";
      } elseif ($den==14) { return "Valentýn";
      } elseif ($den==15) { return "Jiřina";
      } elseif ($den==16) { return "Ljuba";
      } elseif ($den==17) { return "Miloslava";
      } elseif ($den==18) { return "Gizela";
      } elseif ($den==19) { return "Patrik";
      } elseif ($den==20) { return "Oldřich";
      } elseif ($den==21) { return "Lenka";
      } elseif ($den==22) { return "Petr";
      } elseif ($den==23) { return "Svatopluk";
      } elseif ($den==24) { return "Matěj";
      } elseif ($den==25) { return "Liliana";
      } elseif ($den==26) { return "Dorota";
      } elseif ($den==27) { return "Alexandr";
      } elseif ($den==28) { return "Lumír";
      } elseif ($den==29) { return "Horymír"; }
    } elseif ($mesic==3) {
      if ($den==1) { return "Bedřich";
      } elseif ($den==2) { return "Anežka";
      } elseif ($den==3) { return "Kamil";
      } elseif ($den==4) { return "Stela";
      } elseif ($den==5) { return "Kazimir";
      } elseif ($den==6) { return "Miroslav";
      } elseif ($den==7) { return "Tomáš";
      } elseif ($den==8) { return "Gabriela";
      } elseif ($den==9) { return "Františka";
      } elseif ($den==10) { return "Viktorie";
      } elseif ($den==11) { return "Anděla";
      } elseif ($den==12) { return "Řehoř";
      } elseif ($den==13) { return "Růžena";
      } elseif ($den==14) { return "Růt a Matylda";
      } elseif ($den==15) { return "Ida";
      } elseif ($den==16) { return "Elena a Herbert";
      } elseif ($den==17) { return "Vlastimil";
      } elseif ($den==18) { return "Eduard";
      } elseif ($den==19) { return "Josef";
      } elseif ($den==20) { return "Světlana";
      } elseif ($den==21) { return "Radek";
      } elseif ($den==22) { return "Leona";
      } elseif ($den==23) { return "Ivona";
      } elseif ($den==24) { return "Gabriel";
      } elseif ($den==25) { return "Marian";
      } elseif ($den==26) { return "Emanuel";
      } elseif ($den==27) { return "Dita";
      } elseif ($den==28) { return "Soňa";
      } elseif ($den==29) { return "Taťána";
      } elseif ($den==30) { return "Arnošt";
      } elseif ($den==31) { return "Kvido"; }
    } elseif ($mesic==4) {
      if ($den==1) { return "Hugo";
      } elseif ($den==2) { return "Erika";
      } elseif ($den==3) { return "Richard";
      } elseif ($den==4) { return "Ivana";
      } elseif ($den==5) { return "Miroslava";
      } elseif ($den==6) { return "Vendula";
      } elseif ($den==7) { return "Heřman a Hermína";
      } elseif ($den==8) { return "Ema";
      } elseif ($den==9) { return "Dušan";
      } elseif ($den==10) { return "Darja";
      } elseif ($den==11) { return "Izabela";
      } elseif ($den==12) { return "Julius";
      } elseif ($den==13) { return "Aleš";
      } elseif ($den==14) { return "Vincenc";
      } elseif ($den==15) { return "Anastázie";
      } elseif ($den==16) { return "Irena";
      } elseif ($den==17) { return "Rudolf";
      } elseif ($den==18) { return "Valérie";
      } elseif ($den==19) { return "Rostislav";
      } elseif ($den==20) { return "Marcela";
      } elseif ($den==21) { return "Alexandra";
      } elseif ($den==22) { return "Evženie";
      } elseif ($den==23) { return "Vojtěch";
      } elseif ($den==24) { return "Jiří";
      } elseif ($den==25) { return "Marek";
      } elseif ($den==26) { return "Oto";
      } elseif ($den==27) { return "Jaroslav";
      } elseif ($den==28) { return "Vlastislav";
      } elseif ($den==29) { return "Robert";
      } elseif ($den==30) { return "Blahoslav"; }
    } elseif ($mesic==5) {
      if ($den==1) { return "...svátek práce";
      } elseif ($den==2) { return "Zikmund";
      } elseif ($den==3) { return "Alexej";
      } elseif ($den==4) { return "Květoslav";
      } elseif ($den==5) { return "Klaudie";
      } elseif ($den==6) { return "Radoslav";
      } elseif ($den==7) { return "Stanislav";
      } elseif ($den==8) { return "...státní svátek";
      } elseif ($den==9) { return "Ctibor";
      } elseif ($den==10) { return "Blažena";
      } elseif ($den==11) { return "Svatava";
      } elseif ($den==12) { return "Pankrác";
      } elseif ($den==13) { return "Servác";
      } elseif ($den==14) { return "Bonifác";
      } elseif ($den==15) { return "Žofie";
      } elseif ($den==16) { return "Přemysl";
      } elseif ($den==17) { return "Aneta";
      } elseif ($den==18) { return "Nataša";
      } elseif ($den==19) { return "Ivo";
      } elseif ($den==20) { return "Zbyšek";
      } elseif ($den==21) { return "Monika";
      } elseif ($den==22) { return "Emil";
      } elseif ($den==23) { return "Vladimír";
      } elseif ($den==24) { return "Jana";
      } elseif ($den==25) { return "Viola";
      } elseif ($den==26) { return "Filip";
      } elseif ($den==27) { return "Valdemar";
      } elseif ($den==28) { return "Vilém";
      } elseif ($den==29) { return "Maxmilián";
      } elseif ($den==30) { return "Ferdinand";
      } elseif ($den==31) { return "Kamila"; }
    } elseif ($mesic==6) {
      if ($den==1) { return "Laura";
      } elseif ($den==2) { return "Jarmil";
      } elseif ($den==3) { return "Tamara";
      } elseif ($den==4) { return "Dalibor";
      } elseif ($den==5) { return "Dobroslav";
      } elseif ($den==6) { return "Norbert";
      } elseif ($den==7) { return "Iveta a Slavoj";
      } elseif ($den==8) { return "Medard";
      } elseif ($den==9) { return "Stanislava";
      } elseif ($den==10) { return "Gita";
      } elseif ($den==11) { return "Bruno";
      } elseif ($den==12) { return "Antonie";
      } elseif ($den==13) { return "Antonín";
      } elseif ($den==14) { return "Roland";
      } elseif ($den==15) { return "Vít";
      } elseif ($den==16) { return "Zbyněk";
      } elseif ($den==17) { return "Adolf";
      } elseif ($den==18) { return "Milan";
      } elseif ($den==19) { return "Leoš";
      } elseif ($den==20) { return "Květa";
      } elseif ($den==21) { return "Alois";
      } elseif ($den==22) { return "Pavla";
      } elseif ($den==23) { return "Zdeňka";
      } elseif ($den==24) { return "Jan";
      } elseif ($den==25) { return "Ivan";
      } elseif ($den==26) { return "Adriana";
      } elseif ($den==27) { return "Ladislav";
      } elseif ($den==28) { return "Lubomír";
      } elseif ($den==29) { return "Petr a Pavel";
      } elseif ($den==30) { return "Šárka"; }
    } elseif ($mesic==7) {
      if ($den==1) { return "Jaroslava";
      } elseif ($den==2) { return "Patricie";
      } elseif ($den==3) { return "Radomír";
      } elseif ($den==4) { return "Prokop";
      } elseif ($den==5) { return "Cyril a Metoděj";
      } elseif ($den==6) { return "Mistr Jan Hus";
      } elseif ($den==7) { return "Bohuslava";
      } elseif ($den==8) { return "Nora";
      } elseif ($den==9) { return "Drahoslava";
      } elseif ($den==10) { return "Libuše a Amálie";
      } elseif ($den==11) { return "Olga";
      } elseif ($den==12) { return "Bořek";
      } elseif ($den==13) { return "Markéta";
      } elseif ($den==14) { return "Karolína";
      } elseif ($den==15) { return "Jindřich";
      } elseif ($den==16) { return "Luboš";
      } elseif ($den==17) { return "Martina";
      } elseif ($den==18) { return "Drahomíra";
      } elseif ($den==19) { return "Čeněk";
      } elseif ($den==20) { return "Ilja";
      } elseif ($den==21) { return "Vítězslav";
      } elseif ($den==22) { return "Magdaléna";
      } elseif ($den==23) { return "Libor";
      } elseif ($den==24) { return "Kristýna";
      } elseif ($den==25) { return "Jakub";
      } elseif ($den==26) { return "Anna";
      } elseif ($den==27) { return "Věroslav";
      } elseif ($den==28) { return "Viktor";
      } elseif ($den==29) { return "Marta";
      } elseif ($den==30) { return "Bořivoj";
      } elseif ($den==31) { return "Ignác"; }
    } elseif ($mesic==8) {
      if ($den==1) { return "Oskar";
      } elseif ($den==2) { return "Gustav";
      } elseif ($den==3) { return "Miluše";
      } elseif ($den==4) { return "Dominik";
      } elseif ($den==5) { return "Kristian";
      } elseif ($den==6) { return "Oldřiška";
      } elseif ($den==7) { return "Lada";
      } elseif ($den==8) { return "Soběslav";
      } elseif ($den==9) { return "Roman";
      } elseif ($den==10) { return "Vavřinec";
      } elseif ($den==11) { return "Zuzana";
      } elseif ($den==12) { return "Klára";
      } elseif ($den==13) { return "Alena";
      } elseif ($den==14) { return "Alan";
      } elseif ($den==15) { return "Hana";
      } elseif ($den==16) { return "Jáchym";
      } elseif ($den==17) { return "Petra";
      } elseif ($den==18) { return "Helena";
      } elseif ($den==19) { return "Ludvík";
      } elseif ($den==20) { return "Bernard";
      } elseif ($den==21) { return "Johana";
      } elseif ($den==22) { return "Bohuslav";
      } elseif ($den==23) { return "Sandra";
      } elseif ($den==24) { return "Bartoloměj";
      } elseif ($den==25) { return "Radim";
      } elseif ($den==26) { return "Luděk";
      } elseif ($den==27) { return "Otakar";
      } elseif ($den==28) { return "Augustýn";
      } elseif ($den==29) { return "Evelína";
      } elseif ($den==30) { return "Vladěna";
      } elseif ($den==31) { return "Pavlína"; }
    } elseif ($mesic==9) {
      if ($den==1) { return "Linda a Samuel";
      } elseif ($den==2) { return "Adéla";
      } elseif ($den==3) { return "Bronislav";
      } elseif ($den==4) { return "Jindřiška";
      } elseif ($den==5) { return "Boris";
      } elseif ($den==6) { return "Boleslav";
      } elseif ($den==7) { return "Regína";
      } elseif ($den==8) { return "Mariana";
      } elseif ($den==9) { return "Daniela";
      } elseif ($den==10) { return "Irma";
      } elseif ($den==11) { return "Denisa";
      } elseif ($den==12) { return "Marie";
      } elseif ($den==13) { return "Lubor";
      } elseif ($den==14) { return "Radka";
      } elseif ($den==15) { return "Jolana";
      } elseif ($den==16) { return "Ludmila";
      } elseif ($den==17) { return "Naděžda";
      } elseif ($den==18) { return "Kryštof";
      } elseif ($den==19) { return "Zita";
      } elseif ($den==20) { return "Oleg";
      } elseif ($den==21) { return "Matouš";
      } elseif ($den==22) { return "Darina";
      } elseif ($den==23) { return "Berta";
      } elseif ($den==24) { return "Jaromír";
      } elseif ($den==25) { return "Zlata";
      } elseif ($den==26) { return "Andrea";
      } elseif ($den==27) { return "Jonáš";
      } elseif ($den==28) { return "Václav";
      } elseif ($den==29) { return "Michal";
      } elseif ($den==30) { return "Jeroným"; }
    } elseif ($mesic==10) {
      if ($den==1) { return "Igor";
      } elseif ($den==2) { return "Olivie a Oliver";
      } elseif ($den==3) { return "Bohumil";
      } elseif ($den==4) { return "František";
      } elseif ($den==5) { return "Eliška";
      } elseif ($den==6) { return "Hanuš";
      } elseif ($den==7) { return "Justýna";
      } elseif ($den==8) { return "Věra";
      } elseif ($den==9) { return "Štefan a Sára";
      } elseif ($den==10) { return "Marina";
      } elseif ($den==11) { return "Andrej";
      } elseif ($den==12) { return "Marcel";
      } elseif ($den==13) { return "Renáta";
      } elseif ($den==14) { return "Agáta";
      } elseif ($den==15) { return "Tereza";
      } elseif ($den==16) { return "Havel";
      } elseif ($den==17) { return "Hedvika";
      } elseif ($den==18) { return "Lukáš";
      } elseif ($den==19) { return "Michaela";
      } elseif ($den==20) { return "Vendelín";
      } elseif ($den==21) { return "Brigita";
      } elseif ($den==22) { return "Sabina";
      } elseif ($den==23) { return "Teodor";
      } elseif ($den==24) { return "Nina";
      } elseif ($den==25) { return "Beáta";
      } elseif ($den==26) { return "Erik";
      } elseif ($den==27) { return "Šarlota a Zoe";
      } elseif ($den==28) { return "Jidáš";
      } elseif ($den==29) { return "Silvie";
      } elseif ($den==30) { return "Tadeáš";
      } elseif ($den==31) { return "Štěpánka"; }
    } elseif ($mesic==11) {
      if ($den==1) { return "Felix";
      } elseif ($den==2) { return "...památka zesnulých";
      } elseif ($den==3) { return "Hubert";
      } elseif ($den==4) { return "Karel";
      } elseif ($den==5) { return "Miriam";
      } elseif ($den==6) { return "Liběna";
      } elseif ($den==7) { return "Saskie";
      } elseif ($den==8) { return "Bohumír";
      } elseif ($den==9) { return "Bohdan";
      } elseif ($den==10) { return "Evžen";
      } elseif ($den==11) { return "Martin";
      } elseif ($den==12) { return "Benedikt";
      } elseif ($den==13) { return "Tibor";
      } elseif ($den==14) { return "Sáva";
      } elseif ($den==15) { return "Leopold";
      } elseif ($den==16) { return "Otmar";
      } elseif ($den==17) { return "Mahulena";
      } elseif ($den==18) { return "Romana";
      } elseif ($den==19) { return "Alžběta";
      } elseif ($den==20) { return "Nikola";
      } elseif ($den==21) { return "Albert";
      } elseif ($den==22) { return "Cecílie";
      } elseif ($den==23) { return "Klement";
      } elseif ($den==24) { return "Emílie";
      } elseif ($den==25) { return "Kateřina";
      } elseif ($den==26) { return "Artur";
      } elseif ($den==27) { return "Xenie";
      } elseif ($den==28) { return "René";
      } elseif ($den==29) { return "Zina";
      } elseif ($den==30) { return "Ondřej"; }
    } elseif ($mesic==12) {
      if ($den==1) { return "Iva";
      } elseif ($den==2) { return "Blanka";
      } elseif ($den==3) { return "Svatoslav";
      } elseif ($den==4) { return "Barbora";
      } elseif ($den==5) { return "Jitka";
      } elseif ($den==6) { return "Mikuláš";
      } elseif ($den==7) { return "Ambrož a Aenjamín";
      } elseif ($den==8) { return "Květoslava";
      } elseif ($den==9) { return "Vratislav";
      } elseif ($den==10) { return "Julie";
      } elseif ($den==11) { return "Dana";
      } elseif ($den==12) { return "Simona";
      } elseif ($den==13) { return "Lucie";
      } elseif ($den==14) { return "Lýdie";
      } elseif ($den==15) { return "Radana a Radan";
      } elseif ($den==16) { return "Albína";
      } elseif ($den==17) { return "Daniel";
      } elseif ($den==18) { return "Miloslav";
      } elseif ($den==19) { return "Ester";
      } elseif ($den==20) { return "Dagmar";
      } elseif ($den==21) { return "Natálie";
      } elseif ($den==22) { return "Šimon";
      } elseif ($den==23) { return "Vlasta";
      } elseif ($den==24) { return "Adam a Eva";
      } elseif ($den==25) { return "...1. svátek vánoční";
      } elseif ($den==26) { return "Štěpán";
      } elseif ($den==27) { return "Žaneta";
      } elseif ($den==28) { return "Bohumila";
      } elseif ($den==29) { return "Judita";
      } elseif ($den==30) { return "David";
      } elseif ($den==31) { return "Silvestr"; }
    }
  }
}
?>
